#coding=utf-8
'''
El modulo variables almacena variables que necesitamos en otros modulos
'''
filaprecio = []
filatipo = []
filacli = ()
listclientes = ()
treeclientes = ()
treereservas = ()
treeservicios = ()
treeserviciosfac = ()
listreservas =()
menslabel = ()
mensfac = ()
fac = ()
labelser = ()
listado = ()
lblfac = ()
vencalendar = None
calendar = None
filahab = ()
filarbtser = ()
entprecios = ()
labelprecios = ()
filaser = ()
entser = ()
filarbt = ()
treehab = ()
listhab = ()
listservicios = ()
listfacturas = ()
venacercade = None
venprecios = None
panel = None
listcmbhab = ()
cmbhab = None
filareserva = ()
semaforo = None
check = ()
filechooserbackup = None
neobackup = None
numhabres = None
reserva = None
vendialogsalir = None
t = None
cod = None
switch = None
